all_scenes = {
    1: "Rainbow",
    2: "Flowing",
    3: "Heartbeat",
    4: "Red",
    5: "Green",
    6: "Blue",
    7: "Alarm",
    8: "Flash",
    9: "Breathing",
    10: "Feel Green",
    11: "Sunset",
    12: "Rainbow Double way",
    13: "Mixcolor Rainfall Flowing",
    14: "Red Blank Flowing",
    15: "Blue Blank Flowing",
    16: "Green Blank Flowing",
    17: "Purple Blank Flowing",
    18: "Cyan Blank Flowing",
    19: "Yellow Blank Flowing",
    20: "White Blank Flowing",
    21: "Multiple color Flowing",
    22: "Mixcolor Wave Flowing",
    23: "Red Flowing",
    24: "Blue Flowing",
    25: "Green Flowing",
    26: "Purple Flowing",
    27: "Cyan Flowing",
    28: "Yellow Flowing",
    29: "White Flowing",
    30: "Mixcolor Flowing",
    31: "WRW Flowing",
    32: "WBW Flowing",
    33: "WGW Flowing",
    34: "WPW Flowing",
    35: "WCW Flowing",
    36: "WYW Flowing",
    37: "Single Mixcolor Flowing",
    38: "Single Red Flowing",
    39: "Single Blue Flowing",
    40: "Single Green Flowing",
    41: "Single Purple Flowing",
    42: "Single Cyan Flowing",
    43: "Single Yellow Flowing",
    44: "Single White Flowing",
    45: "Red Back Blue Flowing",
    46: "Red Back Green Flowing",
    47: "Red Back Purple Flowing",
    48: "Red Back Cyan Flowing",
    49: "Red Back Yellow Flowing",
    50: "Red Back White Flowing",
    51: "Blue Back Green Flowing",
    52: "Blue Back Purple Flowing",
    53: "Blue Back Cyan Flowing",
    54: "Blue Back Yellow Flowing",
    55: "Blue Back White Flowing",
    56: "Green Back Purple Flowing",
    57: "Green Back Cyan Flowing",
    58: "Green Back Yellow Flowing",
    59: "Green Back White Flowing",
    60: "Purple Back Cyan Flowing",
    61: "Purple Back Yellow Flowing",
    62: "Purple Back White Flowing",
    63: "Cyan Back Yellow Flowing",
    64: "Cyan Back White Flowing",
    65: "Yellow Back White Flowing",
    66: "Red Building Blocks",
    67: "Blue Building Blocks",
    68: "Green Building Blocks",
    69: "Purple Building Blocks",
    70: "Cyan Building Blocks",
    71: "Yellow Building Blocks",
    72: "White Building Blocks",
    73: "BWP Mixcolor Flowing",
    74: "GWR Mixcolor Flowing",
    75: "BWR Mixcolor Flowing",
    76: "RP Mixcolor Flowing",
    77: "RW Mixcolor Flowing",
    78: "RB Mixcolor Flowing",
    79: "Red Point Back Blue Flowing",
    80: "Blue Point Back Green Flowing",
    81: "Green Point Back Purple Flowing",
    82: "Purple Point Back Cyan Flowing",
    83: "Cyan Point Back Yellow Flowing",
    84: "White Point Red Blue Flowing",
    85: "Flowing 2",
    86: "Purple Open Way",
    87: "Purple close Way",
    88: "Rainbow Music Open Way",
    89: "Rainbow Music close Way",
    90: "Cyan flowing Music Open Way",
    91: "Cyan flowing Music close Way",
    92: "Mixcolor flowing Music Open Way",
    93: "Mixcolor flowing fade Music Open",
}
